config/routes.rb
Rails.application.routes.draw do
  resources :cases

  root "cases#index"
end

app/models/case.rb
class Case < ActiveRecord::Base
  has_one :patient
  has_many :treatments
  accepts_nested_attributes_for :patient,
                                :reject_if => :all_blank,
                                :allow_destroy => true
  accepts_nested_attributes_for :treatments,
                                :reject_if => :all_blank,
                                :allow_destroy => true

  validates :name, presence: true
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :case
end

app/models/treatment.rb
class Treatment < ActiveRecord::Base
  belongs_to :case
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_action :find_case, only: [:show, :edit, :update, :destroy]

  def index
    @cases = Case.all
  end

  def show
  end

  def new
    @case = Case.new
  end

  def create
    @case = Case.new(case_params)

    if @case.save
      redirect_to @case
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @case.update(case_params)
      redirect_to @case
    else
      render 'edit'
    end
  end

  def destroy
    @case.destroy
    redirect_to root_path
  end

  private

  def case_params
    params.require(:case).permit(:name, :notes, :appointment, 
      patient_attributes: [:id, :name, :age, :_destroy], 
      treatment_attributes: [:id, :name, :price, :_destroy])
  end

  def find_case
    @case = Case.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/views/cases/_form.html.erb
<%= simple_form_for @case do |f| %>
  <div class='row'>
    <div class='col-md-6'>
      <%= f.input :name, label: "Case name" %>
      <%= f.input :appointment, as: :date, label: "Appointment" %>
      <%= f.input :notes, label: "Description/Notes" %>
      
    </div>
    <div class='col-md-6'>
      <%= f.simple_fields_for :treatments do |treatment| %>
        <%= render 'treatment_fields', f: treatment %>
      <% end %>
        <%= link_to_add_association 'Add Treatment', f, :treatments %>

    </div>
    <%= f.button :submit %>
  </div>

<% end %>

app/views/cases/_treatment_fields.html.erb
<div class='nested-fields'>
  <%= f.input :name %>
  <%= f.input :price %>
  <%= link_to_remove_association 'Remove', f %>
</div>

app/views/cases/edit.html.erb
<div class='container'>
  <h2>Edit Case</h2>
  <%= render 'form' %>
</div>

app/views/cases/index.html.erb
<div class='container'>
  <% @cases.each do |c| %>
    <%= link_to c.name, case_path(c) %>
    <br />
  <% end %>

  <%= link_to 'New Case', new_case_path %>
</div>  

app/views/cases/new.html.erb
<div class='container'>
  <h2>New Case</h2>
  <%= render 'form' %>
</div>

app/views/cases/show.html.erb
<div class='container'>
  <%= div_for @case do %>
    <%= @case.name %>
    <%= @case.appointment %>
    <%= @case.notes %>
  <% end %>

  <%= link_to 'Home', cases_path %>
  <%= link_to 'Edit', edit_case_path %>
  <%= link_to 'Delete', case_path, method: :delete, data: { confirm: "Are you sure?" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Glory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "Glory", cases_path %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "New Case", new_case_path %>
        </li>
      </ul>
    </div>
  </nav>

<%= yield %>

</body>
</html>